// app/org/[orgSlug]/components/MembersManagement/mockData.ts
// MembersManagement/mockData - Mock data for members management

import { Member, PendingInvitation } from './index';

export const mockMembers: Member[] = [
  {
    id: 'mem-001',
    userId: 'user-001',
    organizationId: 'org-001',
    firstName: 'สมชาย',
    lastName: 'ใจดี',
    email: 'somchai@siriraj.go.th',
    username: 'somchai.jaidee',
    phone: '081-234-5678',
    role: 'OWNER',
    isOwner: true,
    isActive: true,
    joinedAt: '2024-01-15T08:30:00Z',
    lastActiveAt: '2024-12-20T14:30:00Z',
    status: 'ACTIVE',
    permissions: ['*'],
    department: 'คลังยาหลัก',
  },
  {
    id: 'mem-002',
    userId: 'user-002',
    organizationId: 'org-001',
    firstName: 'มาลี',
    lastName: 'รักษา',
    email: 'malee.raksa@siriraj.go.th',
    username: 'malee.r',
    phone: '081-345-6789',
    role: 'ADMIN',
    isOwner: false,
    isActive: true,
    joinedAt: '2024-02-01T09:15:00Z',
    lastActiveAt: '2024-12-20T13:45:00Z',
    status: 'ACTIVE',
    permissions: [
      'departments.create',
      'departments.update',
      'products.create',
      'products.update',
      'users.invite',
      'transfers.approve'
    ],
    department: 'ห้องฉุกเฉิน (ER)',
  },
  {
    id: 'mem-003',
    userId: 'user-003',
    organizationId: 'org-001',
    firstName: 'ประยุทธ',
    lastName: 'ดูแล',
    email: 'prayuth.dulal@siriraj.go.th',
    username: 'prayuth.d',
    phone: '081-456-7890',
    role: 'ADMIN',
    isOwner: false,
    isActive: true,
    joinedAt: '2024-02-15T10:00:00Z',
    lastActiveAt: '2024-12-20T11:20:00Z',
    status: 'ACTIVE',
    permissions: [
      'departments.create',
      'departments.update',
      'products.create',
      'products.update',
      'users.invite',
      'transfers.approve'
    ],
    department: 'หอผู้ป่วยใน (IPD)',
  },
  {
    id: 'mem-004',
    userId: 'user-004',
    organizationId: 'org-001',
    firstName: 'สุดา',
    lastName: 'อบอุ่น',
    email: 'suda.obaun@siriraj.go.th',
    username: 'suda.warm',
    phone: '081-567-8901',
    role: 'MEMBER',
    isOwner: false,
    isActive: true,
    joinedAt: '2024-03-01T08:45:00Z',
    lastActiveAt: '2024-12-20T15:10:00Z',
    status: 'ACTIVE',
    permissions: [
      'stocks.read',
      'stocks.adjust',
      'products.read',
      'transfers.create',
      'transfers.receive'
    ],
    department: 'ผู้ป่วยนอก (OPD)',
  },
  {
    id: 'mem-005',
    userId: 'user-005',
    organizationId: 'org-001',
    firstName: 'สุรชัย',
    lastName: 'ผ่า',
    email: 'surachai.pah@siriraj.go.th',
    username: 'surachai.surgeon',
    phone: '081-678-9012',
    role: 'MEMBER',
    isOwner: false,
    isActive: true,
    joinedAt: '2024-03-15T09:30:00Z',
    lastActiveAt: '2024-12-19T16:45:00Z',
    status: 'ACTIVE',
    permissions: [
      'stocks.read',
      'stocks.adjust',
      'products.read',
      'transfers.create',
      'transfers.receive'
    ],
    department: 'ห้องผ่าตัด (OR)',
  },
  {
    id: 'mem-006',
    userId: 'user-006',
    organizationId: 'org-001',
    firstName: 'วิทยา',
    lastName: 'วิเคราะห์',
    email: 'wittaya.analyze@siriraj.go.th',
    username: 'wittaya.lab',
    phone: '081-789-0123',
    role: 'MEMBER',
    isOwner: false,
    isActive: true,
    joinedAt: '2024-04-01T07:20:00Z',
    lastActiveAt: '2024-12-20T12:30:00Z',
    status: 'ACTIVE',
    permissions: [
      'stocks.read',
      'stocks.adjust',
      'products.read',
      'transfers.create',
      'transfers.receive'
    ],
    department: 'ห้องปฏิบัติการ (LAB)',
  },
  {
    id: 'mem-007',
    userId: 'user-007',
    organizationId: 'org-001',
    firstName: 'เภสัช',
    lastName: 'จ่ายยา',
    email: 'pharmacy.dispense@siriraj.go.th',
    username: 'phesach.med',
    phone: '081-890-1234',
    role: 'MEMBER',
    isOwner: false,
    isActive: true,
    joinedAt: '2024-04-15T08:00:00Z',
    lastActiveAt: '2024-12-20T10:15:00Z',
    status: 'ACTIVE',
    permissions: [
      'stocks.read',
      'stocks.adjust',
      'products.read',
      'transfers.create',
      'transfers.receive'
    ],
    department: 'ร้านยา (PHARMACY)',
  },
  {
    id: 'mem-008',
    userId: 'user-008',
    organizationId: 'org-001',
    firstName: 'วิกฤต',
    lastName: 'ช่วยชีวิต',
    email: 'wikrit.save@siriraj.go.th',
    username: 'wikrit.icu',
    phone: '081-901-2345',
    role: 'MEMBER',
    isOwner: false,
    isActive: true,
    joinedAt: '2024-05-01T06:45:00Z',
    lastActiveAt: '2024-12-20T09:20:00Z',
    status: 'ACTIVE',
    permissions: [
      'stocks.read',
      'stocks.adjust',
      'products.read',
      'transfers.create',
      'transfers.receive'
    ],
    department: 'ICU',
  },
  {
    id: 'mem-009',
    userId: 'user-009',
    organizationId: 'org-001',
    firstName: 'ณัฐวุฒิ',
    lastName: 'รอการอนุมัติ',
    email: 'natthawut.pending@siriraj.go.th',
    username: 'natthawut.new',
    phone: '081-012-3456',
    role: 'MEMBER',
    isOwner: false,
    isActive: false,
    joinedAt: '2024-12-18T14:30:00Z',
    lastActiveAt: undefined,
    status: 'PENDING',
    permissions: [],
    department: 'รอการมอบหมาย',
  },
  {
    id: 'mem-010',
    userId: 'user-010',
    organizationId: 'org-001',
    firstName: 'กิตติชัย',
    lastName: 'ระงับ',
    email: 'kittisak.suspended@siriraj.go.th',
    username: 'kittisak.old',
    phone: '081-123-4567',
    role: 'MEMBER',
    isOwner: false,
    isActive: false,
    joinedAt: '2024-01-20T10:00:00Z',
    lastActiveAt: '2024-11-15T16:30:00Z',
    status: 'SUSPENDED',
    permissions: [],
    department: 'หอผู้ป่วยใน (IPD)',
  },
];

export const mockInvitations: PendingInvitation[] = [
  {
    id: 'inv-001',
    organizationId: 'org-001',
    inviterId: 'user-001',
    inviterName: 'สมชาย ใจดี',
    inviteeEmail: 'newdoc@siriraj.go.th',
    inviteeUsername: 'newdoctor',
    role: 'MEMBER',
    message: 'ขอเชิญเข้าร่วมทีมแพทย์แผนกใหม่ เพื่อช่วยกันพัฒนาระบบการดูแลผู้ป่วย',
    status: 'PENDING',
    expiresAt: '2024-12-27T23:59:59Z',
    createdAt: '2024-12-20T10:30:00Z',
  },
  {
    id: 'inv-002',
    organizationId: 'org-001',
    inviterId: 'user-002',
    inviterName: 'มาลี รักษา',
    inviteeEmail: 'nurse.new@siriraj.go.th',
    inviteeUsername: undefined,
    role: 'MEMBER',
    message: 'เชิญเข้าร่วมทีมพยาบาลห้องฉุกเฉิน ต้องการคนที่มีประสบการณ์ในการดูแลผู้ป่วยวิกฤต',
    status: 'PENDING',
    expiresAt: '2024-12-25T23:59:59Z',
    createdAt: '2024-12-18T14:15:00Z',
  },
  {
    id: 'inv-003',
    organizationId: 'org-001',
    inviterId: 'user-001',
    inviterName: 'สมชาย ใจดี',
    inviteeEmail: 'admin.new@siriraj.go.th',
    inviteeUsername: 'admin.hospital',
    role: 'ADMIN',
    message: 'เชิญเป็นผู้ดูแลระบบสำหรับการจัดการองค์กร มีประสบการณ์ด้าน IT และการจัดการ',
    status: 'PENDING',
    expiresAt: '2024-12-28T23:59:59Z',
    createdAt: '2024-12-21T09:00:00Z',
  },
  {
    id: 'inv-004',
    organizationId: 'org-001',
    inviterId: 'user-003',
    inviterName: 'ประยุทธ ดูแล',
    inviteeEmail: 'pharmacist.expired@siriraj.go.th',
    inviteeUsername: undefined,
    role: 'MEMBER',
    message: 'เชิญเข้าร่วมทีมเภสัชกรรมคลังยาหลัก',
    status: 'EXPIRED',
    expiresAt: '2024-12-15T23:59:59Z',
    createdAt: '2024-12-08T11:20:00Z',
  },
  {
    id: 'inv-005',
    organizationId: 'org-001',
    inviterId: 'user-002',
    inviterName: 'มาลี รักษา',
    inviteeEmail: 'declined.user@siriraj.go.th',
    inviteeUsername: 'user.decline',
    role: 'MEMBER',
    message: 'เชิญเข้าร่วมทีมแพทย์',
    status: 'DECLINED',
    expiresAt: '2024-12-30T23:59:59Z',
    createdAt: '2024-12-10T16:45:00Z',
  },
];